spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    使用的数据库是MySQL，驱动是6.0.3，这是由于数据库和系统时区差异所造成的，在jdbc连接的url后面加上serverTimezone=GMT即可解决问题，如果需要使用gmt+8时区，需要写成GMT%2B8，否则会被解析为空。再一个解决办法就是使用低版本的MySQL jdbc驱动，5.1.28不会存在时区的问题。
    url: jdbc:mysql:///pharmacy_management_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: admin
mybatis:
  config-location: classpath:/mybatis-config.xml

server:
  port: 8081
